### ISSUE TITLE
mod is incompatible with tweakeroo

### ISSUE THREAD

**Issue by rengokyuu** [Alexandra-Myers/Combatify#32]

**Comment by zOnlyKroks** [comment]
Could we get any kind of Log? Like Crash Log or latest Log?

**Comment by Alexandra-Myers** [comment]
I figured out the issue... the arm height injection point was provided by RizeCookey for us, who made it for CookeyMod. This injection point causes CookeyMod to be incompatible with Tweakeroo, which is why Combatify is too.
