### ISSUE TITLE
"Weird Sky Glitch Thing"

### ISSUE THREAD

**Issue by QuartzGeek** [Alexandra-Myers/Combatify#33]
![2023-07-02_11 30 14](https://github.com/Alexandra-Myers/Atlas-Combat/assets/123832719/4833e6bd-47d5-4e55-bf88-eee461b28bc2)
For some reason, the sky doesn't seem to be rendering correctly.
This screenshot was taken with only Atlas Combat, owo lib, and Fabric API in my mods folder
(and only the default resource pack enabled).
Is there any way I can fix this?

**Comment by Alexandra-Myers** [comment]
I honestly don't know what is going on with all of these random rendering bugs...

**Comment by QuartzGeek** [comment]
If it helps any, whenever there's a bit of text on the screen (subtitles, chat messages, F3 screen, pause menu, etc.) the glitch seems to go away until the text disappears. I'm not a coder by any means, but could there possibly be a correlation?

**Comment by Alexandra-Myers** [comment]
No? and it seems inconsistent across different people. Most I have played with showed no graphical issues, but some do, and the cases which do are inconsistent, meanwhile making limited logical sense.

**Comment by RamGemes** [comment]
I have only noticed this issue when using the mod without another mod that reworks the render engine (such as sodium)

**Comment by DreamSt4n** [comment]
Can reproduce with Sodium.

**Comment by DreamSt4n** [comment]
> Reference i

I have noticed this as well.

The first screenshot has no text, and the issue appears. The second screenshot doesn't as text appears on the screen, but the glitch comes back once it has disappeared.

![No Text](https://github.com/Alexandra-Myers/Atlas-Combat/assets/19875208/f84608c2-d9f9-454a-80a2-5bdee1e15b3c)

![Text](https://github.com/Alexandra-Myers/Atlas-Combat/assets/19875208/611449b8-bb1c-4347-9223-9c4b014ecedf)

**Comment by Alexandra-Myers** [comment]
Beta 14 fixes it
