### ISSUE TITLE
Attempting to attack an invalid entity [1.20.1 forge]

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Alexandra-Myers/Combatify#34]
Here's the server log
https://mclo.gs/5fHlHI1
It only happens when this mod is installed

**Comment by zOnlyKroks** [comment]
If you were trying to Attack an Hirschgeist, that May be the Error. [25Jul2023 16:27:00.897] [Server thread/WARN] [Puzzles Lib/]: Unable to parse entry whisperwoods:hirschgeist: No matches found in registry minecraft:entity_type

**Comment by zOnlyKroks** [comment]
The entity seems broken to me

**Comment by xXMolgadoGamer01Xx** [comment]
It's strange, because I don't have the whisperwoods mod installed, the error comes when I install this mod on a server and I right click to the air

**Comment by xXMolgadoGamer01Xx** [comment]
The new latest log: https://mclo.gs/9qlhn9d
The debug log: https://mclo.gs/681qOe9
A video of the problem: https://streamable.com/ay64v4

**Comment by Alexandra-Myers** [comment]
mods?

**Comment by xXMolgadoGamer01Xx** [comment]
![image](https://github.com/Alexandra-Myers/Atlas-Combat/assets/24871116/0422d95f-a790-47ce-8e13-d2d667ddf12e)
Sorry for the late response, I was on vacations

**Comment by Alexandra-Myers** [comment]
fixed in 1.1.8 (almost certainly, anyways)
