### ISSUE TITLE
Issue with some enchantment mods.

### ISSUE THREAD

**Issue by xelotex** [Alexandra-Myers/Combatify#38]
When having universal enchants installed, swords will be able to be enchanted with thorns, and with ensorcellation swords gets shield enchantments.
![2023-08-18_01 31 44](https://github.com/Alexandra-Myers/Combatify/assets/70168682/4e7d0365-7b02-4671-88e2-a5c5e7740e72)

**Comment by zOnlyKroks** [comment]
This should also have been resolved

**Comment by xelotex** [comment]
> This should also have been resolved

It hasn't been resolved.

With combatify/without combatify (this is MC Forge 1.20.1, Combatify 1.1.8.3)
![Captura de pantalla (155)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/72690663-3870-403b-a1b7-d87b6b8385ed)
![Captura de pantalla (153)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/048136f6-4abf-496e-81cf-5552482a8b4c)
:

**Comment by xelotex** [comment]
> This should also have been resolved

It hasn't been resolved.

With combatify/without combatify (this is MC Forge 1.20.1, Combatify 1.1.8.3):
![Captura de pantalla (156)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/ae21e78e-7ae4-447a-80bb-59e84b0cf2e7)
![Captura de pantalla (153)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/8402dbce-c0d6-465e-a157-714d5562ac34)

**Comment by Alexandra-Myers** [comment]
I can't see which is which

**Comment by xelotex** [comment]
> I can't see which is which

If you want to reproduce the issue, install combatify and Xerca mod, and try to enchant a sword on the enchanting table. You'll get enchantments meant for the Xerca mod's WarHammer.

"uppercut" and "legerity" aren't enchantments meant for the sword but for the WarHammer, and when i uninstall combatify i get actual enchantments for the sword:

![Captura de pantalla (156)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/74fba138-7c0e-49e2-88ce-a3336a0e8f30)
![Captura de pantalla (153)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/c523cc0c-b1d4-4a36-ba8b-04673588fe1f)

**Comment by xelotex** [comment]
But you did fix the issue with universal enchants, i'm not getting thorns on swords or something like that when playing with combatify and universal enchants. Kinda weird that something similar is happening again with the Xerca mod.

**Comment by Alexandra-Myers** [comment]
I have an idea for what is causing this (maybe fixed in 1.20.6 version I dunno)

**Comment by StunfMC** [comment]
Does this issue still persist in the latest version of Combatify?

**Comment by StunfMC** [comment]
1.2.0 modifies a good amount of code and SHOULD theoretically fix your issue, however it is only for 1.20.6. I will leave this issue open for now while things are being considered.

**Comment by StunfMC** [comment]
Does this issue still persist when using Combatify 1.2.0? Keep in mind that this version is updated to 1.20.6 and may not work with mods that haven’t updated yet.
