### ISSUE TITLE
[1.20.1] [fml] Incompat BetterEnd mod

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Combatify#44]
Mixing MobEffectMixin from mixins.atlascombat.json into net.minecraft.world.effect.MobEffect **fails with BetterEnd**.

Tutorial to get BetterEnd [fabric] running:
1. Install Sinytra Connector + Dependency
2. Install BetterEnd v4.0.9 + Dependency
3. Install Combatify
4. Read debug below:

Debug (ln 1638):
[debug.log](https://github.com/Alexandra-Myers/Combatify/files/12467410/debug.log)

Client loads perfectly without combatify.

**Comment by Alexandra-Myers** [comment]
do you know why this crash occurs?

**Comment by Cixon** [comment]
> do you know why this crash occurs?

I believe it has something to do with the MobEffectMixin for Combatify but I’m unsure. Perhaps maybe @su5ed knows? I mean, the mod works fine with Sinytra alone and even with BClib but as soon as BetterEnd is added to the equation, client no longer finishes start-up phase…

**Comment by Alexandra-Myers** [comment]
it seems unrelated, no really good info here

**Comment by Cixon** [comment]
I attempted to DM Su5eD regarding the matter in hopes there’s a way for devs to tunnel compat for fabric mods using Sinytra but that was 3 days ago…

**Comment by Cixon** [comment]
> it seems unrelated, no really good info here

It’s possible this bug isn’t Combatify’s fault. Perhaps I’ll redirect this ticket to Sinytra’s github?

**Comment by Alexandra-Myers** [comment]
would you consider putting this multiloader modpack onto NeoForge? I think having more latest version packs on Neo would be better in the long run (as it gets people used to using Neo over MinecraftForge)

**Comment by Cixon** [comment]
I’m not against it, it would just require a lot of the pre-existing mods I use to support it + I must await curseforge to support Neo as a game type which should be soon, they have Quilt 🤷‍♂️

**Comment by Cixon** [comment]
Though, it will take some time since my Ultimate modpack relies on Sinytra:
https://github.com/Sinytra/Connector/discussions/128#discussioncomment-6835423
