### ISSUE TITLE
Unable to connect to servers on Quilt

### ISSUE THREAD

**Issue by Estrelaura** [Alexandra-Myers/Combatify#46]
Playing on 1.20.1, Quilt 0.20.2, Servers refuse to ping with the mod installed, forcing the connection returns a disconnect.

Server log: 
 com.mojang.authlib.GameProfile@5cb48f86[id=<null>,name=Estrelaura,properties={},legacy=false] (/***) lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class net.minecraft.class_2540 cannot be cast to class net.kyori.adventure.platform.fabric.impl.server.FriendlyByteBufBridge (net.minecraft.class_2540 and net.kyori.adventure.platform.fabric.impl.server.FriendlyByteBufBridge are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @67b92f0a)

**Comment by Alexandra-Myers** [comment]
I use quilt myself...

**Comment by Alexandra-Myers** [comment]
probably fixed given the error
