### ISSUE TITLE
Strength effect from beacon crashes client on apply

### ISSUE THREAD

**Issue by Thresh90** [Alexandra-Myers/Combatify#48]
Minecraft Version 1.20.1
Using Quilt

Whenever the strength potion effect is applied, it crashes the client via this error message:

[error.txt](https://github.com/Alexandra-Myers/Combatify/files/12668562/error.txt)

**Comment by Alexandra-Myers** [comment]
does the server have the mod?
this is kinda what I expected to be honest

**Comment by Thresh90** [comment]
Yep the server has the mod aswell, this happens with strength specifically as me and a friend tested it with a beacon

**Comment by Thresh90** [comment]
I'll see if I cant get a log here later today, might have to do with another mod conflicting with it probably.

**Comment by Thresh90** [comment]
[log.txt](https://github.com/Alexandra-Myers/Combatify/files/12676953/log.txt)
Back from work, ran some more tests and from both my friends side and mine aswell, it seems like it only client crashes on servers, not single player.

from what i see the log doesnt tell me much (or maybe it does, probably too inexperienced to know)

**Comment by Alexandra-Myers** [comment]
Fixed in RC 5
