### ISSUE TITLE
[1.20.1] [Forge] 1.18 RC 6 crashes with Obscuria API

### ISSUE THREAD

**Issue by BugmanBugman** [Alexandra-Myers/Combatify#49]
https://gist.github.com/BugmanBugman/d45cca2cd216215c33e85ccc81f6659e A log
Latest log:
Mod: https://www.curseforge.com/minecraft/mc-mods/obscure-api
Tried it with just the 3 mods (Midnight lib combatify and obscuria API)

**Comment by Alexandra-Myers** [comment]
Unaware of the exact issue here. Does this issue still occur?
