### ISSUE TITLE
The game kicks me out of the world.

### ISSUE THREAD

**Issue by xelotex** [Alexandra-Myers/Combatify#51]
The game kicks me out of the world and wont let me the enter the world until i uninstall combatify.
This is on forge and in MC v1.20.1.
![Captura de pantalla (63)](https://github.com/Alexandra-Myers/Combatify/assets/70168682/eef44099-6312-49e6-b883-cec4022bfff4)

**Comment by Alexandra-Myers** [comment]
Already fixed.

**Comment by xelotex** [comment]
Alright, i guess that you're going to release a new update soon with the fix, right?

**Comment by Alexandra-Myers** [comment]
yes

**Comment by xelotex** [comment]
> yes

When does the new update comes out?
