### ISSUE TITLE
Antipatterns in ItemMixin

### ISSUE THREAD

**Issue by Daomephsta** [Alexandra-Myers/Combatify#52]
`ItemMixin.getUseDuration()` replicates `Item.getUseDuration()` with a cancellable `@Inject` to insert a small section of mod code.
This is a very problematic way to implement functionality because:

1. Any injected handlers after a handler using this pattern will silently fail to run
2. It's hard to maintain. Every MC version update requires re-copying and re-adapting the code to cancellable `@Inject`
3, It's legally dubious at best. Minecraft's code is proprietary, so avoid copying it if at all possible.

`@Overwrite` would be a better solution here. It is in fact more compatible than the current approach, because it will not cause other injectors to silently fail. There's probably a way to do without it, but it would be an improvement.

Also should be following Mixin best practices:
* Handler methods private when possible (standard Java best practice to minimise access levels)
* Handler method names describe their purpose not what they inject into (more readable and debuggable)

**Comment by zOnlyKroks** [comment]
Will change that to an override once I find time

**Comment by zOnlyKroks** [comment]
Also gonna try to remove the aw`s

**Comment by Daomephsta** [comment]
> Will change that to an override once I find time

Assuming this is a typo, but just in case, `@Overwrite` is different from overriding a method.
Overriding a method in a mixin has a similar effect to overwriting, but reobfuscation will often fail, and you lose Mixin's overwrite conflict detection.

**Comment by Alexandra-Myers** [comment]
'Twas a typo

**Comment by Alexandra-Myers** [comment]
he just does that sometimes

**Comment by zOnlyKroks** [comment]
> > Will change that to an override once I find time
> 
> Assuming this is a typo, but just in case, `@Overwrite` is different from overriding a method. Overriding a method in a mixin has a similar effect to overwriting, but reobfuscation will often fail, and you lose Mixin's overwrite conflict detection.

Yea did a big fat typo. But fixed in the new branch

**Comment by zOnlyKroks** [comment]
Along with a bunch of other stuff

**Comment by zOnlyKroks** [comment]
Fixed in new branch
