### ISSUE TITLE
Random setting in the fabric mod get randomly changed even if I put them back to normal

### ISSUE THREAD

**Issue by FanBoyHalo** [Alexandra-Myers/Combatify#53]
I was playing with this mod and I loaded in my world I converted from bedrock to Java and the attack cooldown seemed more quick than it actually was and I couldn't auto attack. I'm using the 1.20 1.1.8 release candidate. Please see if you can fix this issue thank you.

**Comment by Alexandra-Myers** [comment]
can you send a video and the config file?

**Comment by FanBoyHalo** [comment]
> can you send a video and the config file?

Nvm all I had to do was restart my pc everything is good now
