### ISSUE TITLE
Swinging with no target in range causes connection time out from server (no crashes) (1.19.2 Lastest Forge Nov 2023)

### ISSUE THREAD

**Issue by ThatGuyJess** [Alexandra-Myers/Combatify#54]
![Screenshot 2023-11-23 170847](https://github.com/Alexandra-Myers/Combatify/assets/106454295/82542a0c-26a2-4368-acec-a1097b73f437)

I love this mod; its best combat mod I've used out of many, so it really got to me that I and my friends get kicked from our server (glad that it doesn't crash though) whenever I swing with no target in range (block or entity). Also since I and some friends are using this awesome mod on a server with no crashes occurring (simply disconnects) I'm not sure if there are any logs I can give?

I am also playing on a server with 220+ mods so could there be a problem there?

I am here to answer any questions;
Thanks

**Comment by Alexandra-Myers** [comment]
you just have to hold out until 1.1.8, sorry

**Comment by ThatGuyJess** [comment]
Please don't apologize, it's actually great news to hear that it will be fixed in a future update. I look forward to being able to play with it; its a fantastic mod. :)
