### ISSUE TITLE
[Fabric 1.19.2] Incompatible with Create 

### ISSUE THREAD

**Issue by forite** [Alexandra-Myers/Combatify#56]
Minecraft 1.19.2
Fabric Loader 0.12.2

Mods Installed:
FAPI 0.76.1
"Atlas Combat" 1.1.7
owo 0.9.3
Create 0.5.1

Expected Behavior: When loading world, upon 100%, the world loads
Observed Behavior: At 100%, the application stalls indefinitely

Steps to Reproduce: 
Install the mods as given
Start Minecraft
Attempt to enter a world
At 100%, it should be observed that the application stalls indefinitely

Potentially useful: It seems that both Create (through porting lib) and Combatify use reach entity attributes 2.4.0 as an internal library.

**Comment by StunfMC** [comment]
You are using an old version of Combatify, and 1.19.2 is no longer supported.
