### ISSUE TITLE
No way to break armor stands

### ISSUE THREAD

**Issue by Treetrain1** [Alexandra-Myers/Combatify#58]
I cannot hit armor stands fast enough for them to break, making them impossible to destroy after placed.

I recognize there are options to change the cooldown, but I do not want to change the values from the default.

**Comment by DreamSt4n** [comment]
This sounds like a skill issue if you ask me

**Comment by not-coded** [comment]
> This sounds like a skill issue if you ask me

dont think he asked you

**Comment by DreamSt4n** [comment]
> > This sounds like a skill issue if you ask me
> 
> dont think he asked you

Don't think he asked you either #FreeSpeech #America #Democracy

**Comment by Alexandra-Myers** [comment]
Don't think I asked your opinion

**Comment by DreamSt4n** [comment]
Woah there pal. This is not #CommunityGuidelines safe. Have fun being reported!

**Comment by Treetrain1** [comment]
> This sounds like a skill issue if you ask me

This sounds like you need to be more productive with your time instead of coming into serious GitHub issues and assuming it is the fault of the issue reporter.

**Comment by DreamSt4n** [comment]
> > This sounds like a skill issue if you ask me
> 
> This sounds like you need to be more productive with your time instead of coming into serious GitHub issues and assuming it is the fault of the issue reporter.

This sounds like you can't take a joke. How dare I make a comment on a public forum!

**Comment by Alexandra-Myers** [comment]
> > > This sounds like a skill issue if you ask me
> > 
> > 
> > This sounds like you need to be more productive with your time instead of coming into serious GitHub issues and assuming it is the fault of the issue reporter.
> 
> This sounds like you can't take a joke. How dare I make a comment on a public forum!

This sounds like you can't comprehend when it is appropriate to make a specific joke!

**Comment by DreamSt4n** [comment]
> > > > This sounds like a skill issue if you ask me
> > > 
> > > 
> > > This sounds like you need to be more productive with your time instead of coming into serious GitHub issues and assuming it is the fault of the issue reporter.
> > 
> > 
> > This sounds like you can't take a joke. How dare I make a comment on a public forum!
> 
> This sounds like you can't comprehend when it is appropriate to make a specific joke!

This sounds like you can't comprehend that people can post whatever they want on a public forum, also you should be backing me here this guy doesn't know what sarcasm is.

**Comment by zOnlyKroks** [comment]
This sounds like y'all should just shut up and fix the error.

**Comment by Alexandra-Myers** [comment]
There *isn't* one. This is a vanilla issue, the plan is expand the improvedMiscEntityAttacks config to include more entities.

**Comment by DreamSt4n** [comment]
How about we all sit back and relax and talk this out over a nice cup of coffee?

**Comment by Alexandra-Myers** [comment]
Was fixed in 1.1.8 lol.
