### ISSUE TITLE
Crossbow accuracy does not work as intended

### ISSUE THREAD

**Issue by Treetrain1** [Alexandra-Myers/Combatify#59]
There is an option titled "Bow Uncertainty AKA Accuracy"
This does not apply to other projectiles like tridents.
It would be nice if there was an option for other projectiles as well, or if that option affected all projectiles.

If this is how the combat test snapshot works, I'd recommend adding a separate option to make that option affect all projectiles.

**Comment by Alexandra-Myers** [comment]
Jeb only specified that bows were changed, but I haven't actually checked if that is the case

**Comment by Alexandra-Myers** [comment]
Yes, bows are the only projectile Jeb changed. Controlling the others is extra, but my main concern is there isn't a good way to do it.

**Comment by Matynns** [comment]
To me this sounds like more of a bug/oversight than intentional by Jens. Do crossbows also have 1.0 inaccuracy?

**Comment by Alexandra-Myers** [comment]
no, they do not, admittedly that much is news to me as well.

**Comment by Alexandra-Myers** [comment]
imma fix that in two seconds

**Comment by not-coded** [comment]
no

**Comment by StunfMC** [comment]
This issue has been fixed in Combatify 1.20.6 1.2.0 RC 2. Please let us know if there are any other issues!
