### ISSUE TITLE
[Feature Request] Configuration for Cooldown Indicator to Appear During Hard Cooldown

### ISSUE THREAD

**Issue by forite** [Alexandra-Myers/Combatify#60]
Configurable Value "Cooldown Indicator Usage" with values during_hard_cooldown and during_soft_cooldown (obviously the names can change, and this can be a boolean config). 
This would change when the visual cooldown indicator appears and allows it to alternatively be used to see when the player can attack again. 

Subjectively, I think that the visual indicator would be more useful in that way since timing matters more when I need to attack as soon as possible, versus when I have enough time to let the weapon fully charge for extra reach.

**Comment by Alexandra-Myers** [comment]
Added for 1.2.0 (new implementation though, should allow for more control over this)
