### ISSUE TITLE
【BUG】SwordBlocking caused the game to crash

### ISSUE THREAD

**Issue by GalaxyZEROX** [Alexandra-Myers/Combatify#62]
When using a weapon with SwordBlocking itself, using the right-click SwordBlocking will cause the game to crash (using weapon: 1.18.2SurvivalPlus-Lightsabers).

**Comment by Alexandra-Myers** [comment]
Fixed in 1.1.8, which I am assuming you are on 1.18.2 1.1.7

**Comment by Alexandra-Myers** [comment]
just hold out for now
