### ISSUE TITLE
Tag corruption when tiered shields, longswords,  or knives are disabled

### ISSUE THREAD

**Issue by Treetrain1** [Alexandra-Myers/Combatify#69]
When any of these options are disabled, the `piglin_loved` tag fails to load.
Additionally, the log is severely spammed.

https://mclo.gs/CLPsyRN

**Comment by Alexandra-Myers** [comment]
fixed in 1.2.0

**Comment by Alexandra-Myers** [comment]
I might patch 1.1.8 too
but that's when I get around to it

**Comment by Treetrain1** [comment]
> fixed in 1.2.0

is that an upcoming update?

**Comment by Alexandra-Myers** [comment]
yes
