### ISSUE TITLE
1.20.4 version?

### ISSUE THREAD

**Issue by thwonn** [Alexandra-Myers/Combatify#71]
Will this mod have a version compatible with 1.20.4? It currently only supports 1.20.1 and 1.20.5 snapshots.

**Comment by StunfMC** [comment]
Combatify will not have a 1.20.4 version at this time, we apologize for the inconvenience. We will update to 1.20.5 once it is complete. See #57 and #68

**Comment by thwonn** [comment]
Will Combatify ever be updated to 1.20.4 (after 1.20.5 is released)?

**Comment by StunfMC** [comment]
> Will Combatify ever be updated to 1.20.4 (after 1.20.5 is released)?

We are not 100% sure at this time as 1.20.4 and 1.20.5 are quite different technically, but we might in the future.
