### ISSUE TITLE
1.20.1 backport

### ISSUE THREAD

**Issue by thwonn** [Alexandra-Myers/Combatify#72]
Is it possible to release a backport of Combatify 1.2.0 to Minecraft 1.20.1 when 1.2.0 is finished?
If you are reading this and not a developer, you should expect this backport to take a long time because of technical changes to items in 1.20.5.

**Comment by Alexandra-Myers** [comment]
I won't discount the possibility, but I don't intend to do it, at least on my own. That being said, 1.2.0 comes with many features users will want, so I can see the intrigue there.

**Comment by lucascoelho07** [comment]
would you atleast fix the tags problem (the one that spams errors in the log)? If this is also what is causing incompatibility with Chai's Inventory Sorter

**Comment by Alexandra-Myers** [comment]
yes, that was apart of 1.1.8 anyways, though fixes are considered for 1.1.8.4 anyways

**Comment by StunfMC** [comment]
While we aren’t certain if 1.2.0 will receive a backport for 1.20.1, a fix for 1.1.8 will be considered. Please stay patient with us and we will let you know once we have more details!
