### ISSUE TITLE
Sky glitching in 1.20-1.1.8.3

### ISSUE THREAD

**Issue by antieksi** [Alexandra-Myers/Combatify#73]
![2024-05-26_11 36 14](https://github.com/Alexandra-Myers/Combatify/assets/95758843/4e362e2d-089f-4727-8127-efa39dd33f75)

In certain times of day, when blocking with shield or sword, a glitch appears on the sky.

Appears both when only Combatify is installed and when Sodium is in the instance alongside it.

Similar to #33 because any text shown on the screen seems to make the glitch disappear.

Also happens with no resourcepacks enabled.

**Comment by StunfMC** [comment]
Just to confirm, this doesn’t happen without Sodium installed?

**Comment by antieksi** [comment]
Yes, as I've written before: I've had this bug even with only Combatify installed.

**Comment by StunfMC** [comment]
> Yes, as I've written before: I've had this bug even with only Combatify installed.

I just wanted to make sure. Can you try turning Shield Indicator off in Video Settings and see if this issue still persists?

**Comment by antieksi** [comment]
Will check it. It is late in my timezone right now, so I'll tell how that turned out in 10+ hours or so.

**Comment by StunfMC** [comment]
> Will check it. It is late in my timezone right now, so I'll tell how that turned out in 10+ hours or so.

No worries, please let us know once you get a chance.

**Comment by antieksi** [comment]
Yes, it doesn't appear with Shield Indicator off. 

![изображение](https://github.com/Alexandra-Myers/Combatify/assets/95758843/41ce3e7a-9d0b-4d4b-9627-80069358904c)

Also something I've noticed: when the Shield Indicator is turned on, hotbar icons become transparent in a way similar to crosshair. Is this normal behavior?

![изображение](https://github.com/Alexandra-Myers/Combatify/assets/95758843/56e208df-e1eb-4ca1-8e67-03fd6b48ac70)

**Comment by StunfMC** [comment]
> Yes, it doesn't appear with Shield Indicator off.
> 
> ![изображение](https://private-user-images.githubusercontent.com/95758843/334103498-41ce3e7a-9d0b-4d4b-9627-80069358904c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjU5ODQsIm5iZiI6MTcxNjgyNTY4NCwicGF0aCI6Ii85NTc1ODg0My8zMzQxMDM0OTgtNDFjZTNlN2EtOWQwYi00ZDRiLTk2MjctODAwNjkzNTg5MDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE2MDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTU3OTYwMzQyNTA4NzA5OGUzMGVkYTQ2Yzg2YTllNWFhNDQxODZjZDE5MmQ4ODE2YTQ0MzdjZTM3MTJkMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GMPqhXWefUsbuur5pX9Q6jEsPJBlJuZqZGAL-w66VPE)
> 
> Also something I've noticed: when the Shield Indicator is turned on, hotbar icons become transparent in a way similar to crosshair. Is this normal behavior?
> 
> ![изображение](https://private-user-images.githubusercontent.com/95758843/334103900-56e208df-e1eb-4ca1-8e67-03fd6b48ac70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjU5ODQsIm5iZiI6MTcxNjgyNTY4NCwicGF0aCI6Ii85NTc1ODg0My8zMzQxMDM5MDAtNTZlMjA4ZGYtZTFlYi00Y2ExLThlNjctMDNmZDZiNDhhYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE2MDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZWFkNjIyNzMwNjU4Nzg4ZjgzZTcwNDYwZjY0OWUyYmVkNGUxNjUwOWM0NjQ5ZGE3NzAxMzZmYTA3ZGExMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KjNtrZlfD_7hdnaUaq1Bplye9I9A8PlmX3oNzwU1inI)

This is similar to an issue we had previously, and it seems it hasn’t been fully fixed. I’ll forward this to Alexandra and see what we can do. Thanks for letting us know!
