### ISSUE TITLE
Incompatibility with MOWZIE's MOBS

### ISSUE THREAD

**Issue by xelotex** [Alexandra-Myers/Combatify#74]
The abilities of the Axe of thousand metals don't work. Idk about other version but it's like this on 1.20.1 forge.

**Comment by StunfMC** [comment]
Can you please provide a log file so we can look into this further?

**Comment by xelotex** [comment]
Here it is

[debug.log](https://github.com/user-attachments/files/15800353/debug.log)
[latest.log](https://github.com/user-attachments/files/15800355/latest.log)

**Comment by xelotex** [comment]
If you left click it does like a swipe attack, and if you crouch and left click it should do a shockwave attack, but that just doesn't happen if combatify its installed. Maybe you can try it out by yourself, test the Axe with only Mowzie's installed and then add combatify.

**Comment by StunfMC** [comment]
Okay, I will forward this to Alexandra and see what we can do. Thank you for letting us know!

**Comment by xelotex** [comment]
So... This was fixed or something? Can we expect a new version of combatify for forge 1.20.1 fixing this?

**Comment by StunfMC** [comment]
A 1.20.1 port is not planned at this time. I meant to close this as not planned.
