### ISSUE TITLE
Cleaving can be put on swords using Enchantment Table

### ISSUE THREAD

**Issue by antieksi** [Alexandra-Myers/Combatify#75]
As the title says, seems like I can put Cleaving on swords using the Enchantment Table. Not sure if this is expected behavior since in the combat snapshots Cleaving is an axe-exclusive enchantment.

![-](https://github.com/Alexandra-Myers/Combatify/assets/95758843/a215f3f1-2bce-4318-bb0e-0ac5d6aba94c)

Less important issue that I've also noticed is that enchantments added in Combatify don't have descriptions that [this mod](https://modrinth.com/mod/enchantment-descriptions) would usually display.

![-](https://github.com/Alexandra-Myers/Combatify/assets/95758843/cca4b56e-d0c1-4071-b4d3-70b24db2acbd)

**Comment by Alexandra-Myers** [comment]
This was already fixed in 1.2.0

**Comment by Alexandra-Myers** [comment]
the description I can add though

**Comment by Alexandra-Myers** [comment]
I am aware, but I can probably fix this in the 1.1.8 patch anyways

**Comment by StunfMC** [comment]
This issue has been fixed in 1.2.0. A 1.20.1 back port is being considered and the progress can be found in #72. Please let us know if there is any other issues!

**Comment by StunfMC** [comment]
This issue has been fixed in Combatify 1.2.0. A 1.20.1 back port is being considered and the progress can be found in #72. Please let us know if there are any other issues!
