### ISSUE TITLE
Combatify is incompatible with Tetra and it´s addons

### ISSUE THREAD

**Issue by Janthebest11** [Alexandra-Myers/Combatify#78]
https://www.curseforge.com/minecraft/mc-mods/tetra

[2024-07-06-10.log](https://github.com/user-attachments/files/16116719/2024-07-06-10.log)

**Comment by Alexandra-Myers** [comment]
I see a lot of issues here, but there is no connection between any of them and Combatify or Tetra; I assume the incompatibility was identified by a binary search but if that is the case then the log given has no info on why

**Comment by Janthebest11** [comment]
nwm somehow made it work
