### ISSUE TITLE
Miss Time not Triggering

### ISSUE THREAD

**Issue by Matynns** [Alexandra-Myers/Combatify#79]
If you start breaking a block while attacking (missing an attack and clicking a block instead of an entity), miss time does not trigger. Instead of having only a 4-tick delay, you get the full delay of your weapon, even if an entity is not attacked. This causes issues with timing attacks.

When holding to attack, this issue seems to trigger only after hitting a block the first time.

**Comment by StunfMC** [comment]
Works as intended.

**Comment by Matynns** [comment]
If this is working as intended, there should be a config option to disable it. This issue is not present in CTS 8c or any combat tests as far as my testing goes.

**Comment by Alexandra-Myers** [comment]
Thank you for testing it. I asked Stunf to try it on 8c but he just wrote it off as intended

**Comment by Alexandra-Myers** [comment]
Fixed for 1.2.3
