### ISSUE TITLE
Cleaving enchantment absent from villager trades and enchanting table rolls

### ISSUE THREAD

**Issue by RC-Barry** [Alexandra-Myers/Combatify#80]
Cleaving is unable to be obtained from villager trades or enchanting table rolls in current version 1.21

**Comment by genericgamedev** [comment]
Seems to be happening to me too. At the very least, they're way less common.

**Comment by Alexandra-Myers** [comment]
Fixed in 1.2.1

**Comment by genericgamedev** [comment]
I see 1.2.2 is also out. Should I go straight to that?

**Comment by Alexandra-Myers** [comment]
yes
